### ISSUE TITLE
Unequal dimensions for 4x6 3d print

### ISSUE THREAD

**Issue by LinuxBozo** [Bastardkb/Charybdis#2]
The instructions say to print out the opposite side of the Charybdis with the sister, Scylla, so you have a complete keyboard. Unfortunately, the dimensions of the two do not match. The Charybdis is approximately 3mm or so higher in profile, making for a very odd experience.

See this image, with `charybdis3_v131.stl` on the left, `Scylla82.stl` on the right:

![Screen Shot 2021-10-19 at 10 33 11 AM](https://user-images.githubusercontent.com/723420/137932862-2111c96d-7bab-43fc-b62d-c1b60c825c95.png)

**Comment by EricDracula** [comment]
Hi all,

I wonder whether this problem has been solved now. I compared the `charybdis3_v131.stl` and `Scylla82.stl` two models and the difference is quite large, not just the height. It was really difficult for me to adjust them in fusion360 to make them match. I want to know if there is a matching model now?

**Comment by bstiq** [comment]
Hello,

This is due to PCB constraints - namely the clearance for the sensor pcb
iirc.
I decided to increase the charybdis height, but keep the scylla a bit lower
as I want everything as low profile as possible.

In practice it's not an issue, I have yet to hear from someone who notices
during use.

What do you mean by large difference between charybdis3_v131.stl and
Scylla82.stl ?
What are you trying to adjust ?

Regards,

*Quentin LEBASTARD*
