### ISSUE TITLE
3x5 Charybdis missing switch notches on thumb switches

### ISSUE THREAD

**Issue by bjvanst** [Bastardkb/Charybdis#5]
Printed the Charybdis 3x5 yesterday and noticed that the two thumb switches are missing the bottom notches for the clips on MX switches.  Confirmed they are missing from the STL and not just an artifact in my print.

**Comment by bstiq** [comment]
Hey, 

This is an issue yes.  
It is fixed in the new v4 skeletyl, but still not on the cnano.

As every new version requires intensive testing, I'm not willing to introduce new files just for this, this is not an issue during build.

I will add those on the next major update.

Thanks for the feedback!

Regards,
